apiVersion: v1
kind: Service
metadata:
  name: go-webapp
  namespace: default
spec:
  selector:
    app: go-webapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
