name: ci

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'helm/**'
            - 'static/**'
jobs:

    build:
        runs-on: ubuntu-latest

        steps:
        -
            name: Checkout repository
            uses: actions/checkout@v4
        
        -
            name: set up GO 1.22.5
            uses: actions/setup-go@v5
            with:
                go-version: 1.22.5 
        
        -
            name: Build application
            run: go build -o go_webapp

        -
            name: Test application
            run: go test ./...
    
    code-quality:
        runs-on: ubuntu-latest
        needs: build

        steps:
        -
            name: Checkout repository
            uses: actions/checkout@v4

        -
            name: Run golangci-lint for static code analysis
            uses: golangci/golangci-lint-action@v6

    
    push:
        runs-on: ubuntu-latest

        needs: build

        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Build and push
            uses: docker/build-push-action@v6
            with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/go_webapp:${{github.run_id}}
    
    updating_the_helm_chart:
        runs-on: ubuntu-latest

        needs: push

        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
            with:
                token: ${{ secrets.TOKEN }}

        -
            name: updating the tag entry in the helm chart
            run: |
                sed -i 's/tag: "[^"]*"/tag: "${{github.run_Id}}"/' Helm/go_webapp-chart/values.yaml
        
        -
            name: Commit and push the changes
            run: |
                git config --global user.email "constantineukah@gmail.com"
                git config --global user.name "iam-ukahconstantine"
                git add Helm/go_webapp-chart/values.yaml
                git commit -m "Updated the tag in the Helm chart"
                git push origin main




        
    
        


